import mongoose, { Document, Schema } from 'mongoose';

export interface IReport extends Document {
  type: 'financial' | 'attendance' | 'booking' | 'expense';
  title: string;
  description: string;
  data: Record<string, any>;
  generatedBy: mongoose.Types.ObjectId;
  period: {
    start: Date;
    end: Date;
  };
  createdAt: Date;
  updatedAt: Date;
}

const reportSchema = new Schema<IReport>(
  {
    type: {
      type: String,
      enum: ['financial', 'attendance', 'booking', 'expense'],
      required: [true, 'Report type is required'],
    },
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
    },
    description: {
      type: String,
      trim: true,
    },
    data: {
      type: Schema.Types.Mixed,
      required: [true, 'Report data is required'],
    },
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'Member',
      required: [true, 'Generated by member is required'],
    },
    period: {
      start: {
        type: Date,
        required: [true, 'Period start date is required'],
      },
      end: {
        type: Date,
        required: [true, 'Period end date is required'],
      },
    },
  },
  {
    timestamps: true,
  }
);

export const Report = mongoose.model<IReport>('Report', reportSchema);

